name: GitHub Pages

on:
  push:
    branches:
      - github-pages
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: arktwin

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 25
          distribution: temurin
          cache: sbt
          cache-dependency-path: arktwin/arktwin/build.sbt

      - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd # v1.1.14

      - name: Generate OpenAPI YAML files
        working-directory: arktwin/arktwin
        run: sbt "edge/run generate-openapi-center ../../pages/dist/swagger-ui/center/arktwin-center.yaml" "edge/run generate-openapi-edge ../../pages/dist/swagger-ui/edge/arktwin-edge.yaml"

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: swagger-api/swagger-ui
          ref: v5.17.14
          path: swagger-ui

      - name: Copy Swagger UI static files
        run: |
          mkdir arktwin/pages/dist/swagger-ui/bundle
          cp swagger-ui/dist/* arktwin/pages/dist/swagger-ui/bundle
          rm arktwin/pages/dist/swagger-ui/bundle/index.html

      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: arktwin/pages/dist

      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        id: deployment
